[black]
args = ["--check"]
help = "Code formatter for python."
fast = true

[black.format]
args = []

[flake8]
args = ["--max-line-length=88"]
help="Code style checker for python."
fast = true

[isort]
args = [
    "--recursive",
    "--multi-line=3",
    "--trailing-comma",
    "--force-grid-wrap=0",
    "--use-parentheses",
    "--lines=88",
    "--check-only"
]
help = "Tool for sorting and cleaning python imports."
fast = true

[isort.format]
args = [
    "--recursive",
    "--multi-line=3",
    "--trailing-comma",
    "--force-grid-wrap=0",
    "--use-parentheses",
    "--lines=88"
]

[mypy]
args = ["--ignore-missing-imports"]
help = "Validate types using mypy."
fast = true

[pylint]
args = ["--disable=C0330,E0401"]
help = "Python code linter"

[pylint.test]
args = ["--disable=C0330,C0103,C0114,C0115,C0116,E1101,E0401"]

[pydocstyle]
args = ["--ignore=D203,D212,D400,D401"]
help = "Tool for python docstring style enforcing"

[pydocstyle.test]
args = ["--ignore=D100,D101,D102,D203,D212,D400,D401"]